

export class ClientGlobalPrefKeys {
  static readonly PREF_NAME: string = 'client_global';
  // Colors 页列表局部颜色
  static readonly COLOR_MODE_LOCAL_IN_COLORS_PAGE: string = 'colorModeLocalInColorsPage';
  // 应用自定义颜色模式
  static readonly COLOR_MODE_LOCAL_IN_APP: string = 'colorModeLocalInApp';
  // 系统的颜色模式
  static readonly COLOR_MODE_LOCAL_IN_SYS: string = 'colorModeLocalInSys';
  // 系统颜色HEX字符串
  static readonly SYS_RESOURCE_HEX_STRING: string = 'sysResourceHexString';
  // 用户隐私协议同意
  static readonly PRIVACY_POLICY_AGREE: string = 'privacyPolicyAgree';
}